# Generated by Django 4.2.2 on 2024-02-09 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="genre",
            field=models.CharField(
                choices=[("engineering", "engineering"), ("personal", "personal")],
                default="misc",
                max_length=20,
            ),
        ),
    ]
