# Generated by Django 4.2.2 on 2024-04-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio_app",
            "0006_project_image_project_semester_alter_blog_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Skills",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("mechanical", "mechanical"), ("soft", "soft")],
                        default="misc",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="portfolio_app/static/default-image.jpg",
                        upload_to="portfolio_app/static/",
                    ),
                ),
            ],
        ),
    ]
