# Generated by Django 4.2.2 on 2024-04-10 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0007_skills"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skills",
            new_name="Skill",
        ),
    ]
