# Generated by Django 4.2.2 on 2024-04-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0008_rename_skills_skill"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="description",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="certification",
            name="image",
            field=models.ImageField(
                default="portfolio_app/static/default-image.jpg",
                upload_to="portfolio_app/static/",
            ),
        ),
        migrations.AlterField(
            model_name="skill",
            name="category",
            field=models.CharField(
                choices=[
                    ("mechanical", "mechanical"),
                    ("coding", "coding"),
                    ("soft", "soft"),
                    ("industry", "industry"),
                    ("misc", "misc"),
                ],
                default="misc",
                max_length=20,
            ),
        ),
    ]
