# Generated by Django 4.2.2 on 2024-04-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "portfolio_app",
            "0009_certification_description_certification_image_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="description",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="education",
            name="graduation_year",
            field=models.CharField(max_length=100),
        ),
    ]
