# Generated by Django 4.2.2 on 2024-04-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0011_workexperience_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexperience",
            name="end_date",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="workexperience",
            name="start_date",
            field=models.CharField(max_length=100),
        ),
    ]
