# Generated by Django 4.2.2 on 2024-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0012_alter_workexperience_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="image",
            field=models.ImageField(
                default="portfolio_app/static/default-image.jpg",
                upload_to="portfolio_app/static/",
            ),
        ),
        migrations.AddField(
            model_name="workexperience",
            name="mentor",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
