# Generated by Django 4.2.2 on 2024-05-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio_app", "0013_workexperience_image_workexperience_mentor"),
    ]

    operations = [
        migrations.AddField(
            model_name="workexperience",
            name="mentor_position",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
